# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Proficiency Exercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftLint'
  # Pods for iOS Proficiency Exercise

  target 'iOS Proficiency ExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS Proficiency ExerciseUITests' do
    # Pods for testing
  end

end
